### ISSUE TITLE
ErrorException: Implicit conversion from float 1654581791.96246 to int loses precision in D:\owenzhang\webman-admin\app\common\middleware\ActionHook.php:111

### ISSUE THREAD

**Issue by owenzhang24** [hsk99/webman-admin#3]
ErrorException: Implicit conversion from float 1654581791.96246 to int loses precision in D:\owenzhang\webman-admin\app\common\middleware\ActionHook.php:111
Stack trace:
#0 [internal function]: {closure}()
#1 D:\owenzhang\webman-admin\app\common\middleware\ActionHook.php(111): date()
#2 D:\owenzhang\webman-admin\app\common\middleware\ActionHook.php(65): app\common\middleware\ActionHook->recordLog()
#3 D:\owenzhang\webman-admin\vendor\workerman\webman-framework\src\App.php(245): app\common\middleware\ActionHook->process()
#4 D:\owenzhang\webman-admin\vendor\workerman\webman-framework\src\App.php(330): Webman\App::Webman\{closure}()
#5 D:\owenzhang\webman-admin\vendor\workerman\webman-framework\src\App.php(147): Webman\App::findRoute()
#6 D:\owenzhang\webman-admin\vendor\workerman\workerman\Connection\TcpConnection.php(638): Webman\App->onMessage()
#7 D:\owenzhang\webman-admin\vendor\workerman\workerman\Events\Select.php(295): Workerman\Connection\TcpConnection->baseRead()
#8 D:\owenzhang\webman-admin\vendor\workerman\workerman\Worker.php(2435): Workerman\Events\Select->loop()
#9 D:\owenzhang\webman-admin\vendor\workerman\workerman\Worker.php(1430): Workerman\Worker->run()
#10 D:\owenzhang\webman-admin\vendor\workerman\workerman\Worker.php(1373): Workerman\Worker::forkWorkersForWindows()
#11 D:\owenzhang\webman-admin\vendor\workerman\workerman\Worker.php(549): Workerman\Worker::forkWorkers()
#12 D:\owenzhang\webman-admin\start.php(112): Workerman\Worker::runAll()
#13 {main}

**Comment by owenzhang24** [comment]
解决办法：
![image](https://user-images.githubusercontent.com/39992479/172307427-40721642-4cc1-493d-8f8d-36283f834551.png)
